#!/usr/bin/env bash
# D1 — generate a production-compliant .env with strong secrets, then let the operator fill the
# cloud LLM keys. The P0.5 boot-guard REJECTS the dev defaults (bravo:bravo, unauthenticated Redis,
# change-me secrets) when ENV=production, so a deploy MUST run this (or an equivalent) first.
#
# Usage:  ./deploy/gen-secrets.sh            # writes .env (refuses to overwrite an existing one)
#         ./deploy/gen-secrets.sh --force    # overwrite
set -euo pipefail
cd "$(dirname "$0")/.."

TARGET=.env
[[ "${1:-}" == "--force" ]] && rm -f "$TARGET"
if [[ -f "$TARGET" ]]; then
  echo "!! $TARGET already exists — refusing to overwrite. Use --force to regenerate." >&2
  exit 1
fi

gen() { openssl rand -hex 32; }
JWT=$(gen); PEPPER=$(gen); PGPASS=$(gen); REDISPASS=$(gen)

cat > "$TARGET" <<EOF
# Generated by deploy/gen-secrets.sh — production secrets. NEVER commit this file.
ENV=production
LOG_LEVEL=INFO

# --- Auth / security (strong, fail-closed boot-guard) ---
JWT_SECRET=${JWT}
MCP_TOKEN_PEPPER=${PEPPER}

# --- Database (compose service name 'postgres'; password matches POSTGRES_PASSWORD) ---
POSTGRES_USER=bravo
POSTGRES_PASSWORD=${PGPASS}
POSTGRES_DB=bravo
DATABASE_URL=postgresql+asyncpg://bravo:${PGPASS}@postgres:5432/bravo

# --- Redis (authenticated; prod overlay enforces --requirepass) ---
REDIS_PASSWORD=${REDISPASS}
REDIS_URL=redis://:${REDISPASS}@redis:6379/0

# --- Embedding: CLOUD for the pilot (no GPU). Corpus text egresses to the embedding API. ---
EMBEDDING_PROVIDER=openai_compatible
EMBEDDING_MODEL=text-embedding-3-small
EMBEDDING_DIM=1536
CLOUD_EMBEDDING_BASE_URL=<FILL: OpenAI-compatible embeddings endpoint>
CLOUD_EMBEDDING_MODEL=text-embedding-3-small
CLOUD_EMBEDDING_API_KEY=<FILL: key>

# --- LLM: cloud (cloud_only pilot). FILL these before boot (boot-guard requires all four). ---
EGRESS_POLICY=cloud_only
CLOUD_ENABLED=true
CLOUD_BASE_URL=<FILL: OpenAI-compatible chat endpoint>
CLOUD_MODEL=<FILL: model id>
CLOUD_API_KEY=<FILL: key>
DEMO_ALLOW_CLOUD_ANSWERS=true

# --- Retrieval quality ---
RERANK_ENABLED=true
RERANK_PROVIDER=llm

# --- Consultant layer (on for dogfood) ---
CONSULTANT_ENABLED=true
EOF

chmod 600 "$TARGET"
echo "Wrote $TARGET with strong JWT/pepper/Postgres/Redis secrets (chmod 600)."
echo "NEXT: fill the <FILL: ...> cloud LLM + embedding values, then run deploy/bootstrap.sh."
echo "Verify boot-guard will pass:  docker compose -f docker-compose.yml -f docker-compose.prod.yml run --rm api python -c 'from app.config import get_settings; get_settings().validate_boot(); print(\"boot-guard OK\")'"
