"""Create one isolated, gitignored WP-00 environment file with fresh local secrets.

It never reads or overwrites .env, never prints a generated value, and defaults cloud egress to
off. Fill an approved rotated provider credential only in the generated local file when A/B
capture is ready.
"""
from __future__ import annotations

import argparse
import secrets
from pathlib import Path


def _secret() -> str:
    return secrets.token_hex(32)


def render(env_file: str) -> str:
    postgres_password = _secret()
    redis_password = _secret()
    api_password = _secret()
    worker_password = _secret()
    return f"""# Generated by scripts/create_wp00_env.py. Never commit or paste this file.\nBRAVO_ENV_FILE={env_file}\nENV=production\nLOG_LEVEL=INFO\n\nPOSTGRES_USER=bravo\nPOSTGRES_PASSWORD={postgres_password}\nPOSTGRES_DB=bravo\nDATABASE_URL=postgresql+asyncpg://bravo:{postgres_password}@postgres:5432/bravo\n\nREDIS_PASSWORD={redis_password}\nREDIS_URL=redis://:{redis_password}@redis:6379/0\n\n# Created by scripts/provision_wp00_runtime_roles.py; keep these DSNs private.\nBRAVO_API_DATABASE_URL=postgresql+asyncpg://bravo_api_login:{api_password}@postgres:5432/bravo\nBRAVO_WORKER_DATABASE_URL=postgresql+asyncpg://bravo_worker_login:{worker_password}@postgres:5432/bravo\n\nJWT_SECRET={_secret()}\nMCP_TOKEN_PEPPER={_secret()}\n\n# Safe containment default. Set CLOUD_* only after rotation in the provider control plane.\nEGRESS_POLICY=hybrid\nCLOUD_ENABLED=false\nCLOUD_BASE_URL=\nCLOUD_MODEL=\nCLOUD_API_KEY=\nDEMO_ALLOW_CLOUD_ANSWERS=false\n\nLLM_LOCAL_BASE_URL=http://host.docker.internal:8001/v1\nLLM_LOCAL_MODEL=Qwen2.5-32B-Instruct-AWQ\nLLM_LOCAL_API_KEY=dummy\nEMBEDDING_PROVIDER=local\nEMBEDDING_MODEL=BAAI/bge-m3\nEMBEDDING_DIM=1024\n\nCONSULTANT_ENABLED=true\nCONSULTANT_EXTERNAL_EXPERT_ENABLED=false\nCONSULTANT_ROLLOUT_PERCENT=100\nCONSULTANT_CONFIG_VERSION=consultant/v1\nCONSULTANT_CURATION_ENABLED=false\nCONSULTANT_STATE_RETENTION_ENABLED=false\nCONSULTANT_STATE_RETENTION_DAYS=0\nNATIVE_RLS_ENABLED=false\n"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=".env.wp00")
    args = parser.parse_args()
    path = Path(args.out)
    if path.exists():
        raise SystemExit(f"Refusing to overwrite existing secret file: {path}")
    path.write_text(render(path.as_posix()), encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    print(f"Created {path}; generated values were not printed. Keep it out of Git.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
